name: iesd-alpine
services:
  httpd:
    build:
        context: .
        dockerfile: Dockerfile
    #image: ruseler/alpine-iesd:latest
    ports:
      - '8080:80'
    volumes:     
     - 'htdocs_data:/usr/share/nginx/html/'
volumes:
  htdocs_data:
    driver: local